### ISSUE TITLE
AppImage

### ISSUE THREAD

**Issue by Israel-** [Israel-/fltk-lightdm#1]
@probonopd How do I package an AppImage that uses pkexec as well?
When using your nice scripts it looks at my desktop file which uses
```desktop
Exec=pkexec fltk-lightdm
```
and then cannot find pkexec (though I actually install it in my travis.yml)
```yml
addons:
  apt:
    packages:
      - policykit-1
```
Do AppImages support pkexec usage... or do I need to mod the exec line somehow?
